export const fundingSolutions = [
  { slug: 'working-capital', anchor: 'working-capital', title: 'Working Capital', range: '$10K-$2M', speed: '24-72 hours after complete file', summary: 'Flexible operating capital for payroll, inventory, marketing, hiring, remodels, and expansion.', useCases: ['Inventory purchases', 'Payroll bridge capital', 'Marketing campaigns', 'Seasonal cash-flow coverage'], qualifications: ['6+ months in business preferred', '$10K+ monthly revenue', 'Active business bank account'], documents: ['Last 3 business bank statements', 'Government ID', 'Voided check or bank letter'] },
  { slug: 'equipment-financing', anchor: 'equipment-financing', title: 'Equipment Financing', range: '$25K-$5M', speed: '2-7 business days', summary: 'Acquire mission-critical equipment while preserving cash and matching payments to useful asset life.', useCases: ['Yellow iron and heavy machinery', 'Medical and dental equipment', 'Trucks and trailers', 'Restaurant and manufacturing equipment'], qualifications: ['Equipment invoice or quote', 'Business revenue supports payment', 'Collateral and vendor review may apply'], documents: ['Equipment quote', 'Bank statements', 'Business formation documents'] },
  { slug: 'sba-loans', anchor: 'sba-loans', title: 'SBA Loans', range: '$50K-$5M', speed: '30-90 days', summary: 'Government-backed loan options for qualified borrowers seeking longer terms and lower-cost capital.', useCases: ['Expansion', 'Debt refinance', 'Owner-occupied real estate', 'Acquisition capital'], qualifications: ['Stronger credit profile usually required', 'Tax returns and financials reviewed', 'Collateral may be requested'], documents: ['Business and personal tax returns', 'P&L and balance sheet', 'Debt schedule'] },
  { slug: 'business-lines-of-credit', anchor: 'business-lines-of-credit', title: 'Business Lines of Credit', range: '$10K-$500K', speed: '1-5 business days', summary: 'Revolving access to capital for operators who need repeatable purchasing power and flexibility.', useCases: ['Recurring inventory', 'Short-term vendor payments', 'Cash-flow timing gaps', 'Emergency reserves'], qualifications: ['Consistent deposits', 'Responsible bank activity', 'Available credit varies by profile'], documents: ['Bank statements', 'Business information', 'Owner identification'] },
  { slug: 'invoice-factoring', anchor: 'invoice-factoring', title: 'Invoice Factoring', range: '$25K-$3M', speed: '3-10 business days', summary: 'Convert eligible B2B receivables into working capital without waiting for customer payment cycles.', useCases: ['Slow-paying customers', 'Staffing and payroll float', 'Large purchase orders', 'Government or enterprise receivables'], qualifications: ['Eligible commercial invoices', 'Customer credit quality reviewed', 'No major invoice disputes'], documents: ['A/R aging report', 'Sample invoices', 'Customer list'] },
  { slug: 'commercial-real-estate', anchor: 'commercial-real-estate', title: 'Commercial Real Estate Financing', range: '$250K-$25M+', speed: '2-8 weeks', summary: 'Capital for acquisition, refinance, bridge, and owner-occupied commercial property strategies.', useCases: ['Acquisition', 'Refinance', 'Bridge financing', 'Renovation and stabilization'], qualifications: ['Property valuation review', 'Debt-service coverage analysis', 'Sponsor experience considered'], documents: ['Rent roll', 'Operating statements', 'Purchase contract or payoff statement'] },
  { slug: 'merchant-cash-advance', anchor: 'merchant-cash-advance', title: 'Merchant Cash Advance', range: '$10K-$1M', speed: 'Same day-48 hours', summary: 'Fast revenue-based funding designed around current sales volume and near-term capital needs.', useCases: ['Urgent opportunities', 'Inventory buys', 'Repairs', 'Short-term working capital'], qualifications: ['Recent business deposits', 'Clear repayment capacity', 'Existing advance balances reviewed'], documents: ['Last 3 bank statements', 'Processing statements when applicable', 'Owner ID'] },
];

export const industries = [
  { slug: 'construction', title: 'Construction', needs: ['Mobilization costs', 'Materials', 'Payroll between draws'], products: ['Working Capital', 'Equipment Financing', 'Invoice Factoring'] },
  { slug: 'healthcare', title: 'Healthcare', needs: ['Equipment upgrades', 'Insurance reimbursement gaps', 'Practice expansion'], products: ['Equipment Financing', 'Lines of Credit', 'SBA Loans'] },
  { slug: 'restaurants', title: 'Restaurants', needs: ['Food inventory', 'Renovations', 'Seasonal staffing'], products: ['Working Capital', 'Merchant Cash Advance', 'Equipment Financing'] },
  { slug: 'trucking-logistics', title: 'Trucking & Logistics', needs: ['Truck repairs', 'Fuel float', 'New routes and trailers'], products: ['Equipment Financing', 'Invoice Factoring', 'Working Capital'] },
  { slug: 'retail', title: 'Retail', needs: ['Inventory cycles', 'Holiday build-up', 'Store improvements'], products: ['Lines of Credit', 'Working Capital', 'Merchant Cash Advance'] },
  { slug: 'professional-services', title: 'Professional Services', needs: ['Hiring', 'Software investments', 'Receivables timing'], products: ['Lines of Credit', 'SBA Loans', 'Working Capital'] },
  { slug: 'manufacturing', title: 'Manufacturing', needs: ['Raw materials', 'Equipment', 'Large purchase orders'], products: ['Equipment Financing', 'Invoice Factoring', 'Working Capital'] },
  { slug: 'automotive', title: 'Automotive', needs: ['Parts inventory', 'Lifts and diagnostic tools', 'Expansion bays'], products: ['Equipment Financing', 'Working Capital', 'Lines of Credit'] },
  { slug: 'ecommerce', title: 'Ecommerce', needs: ['Inventory buys', 'Ad spend', 'Fulfillment expenses'], products: ['Working Capital', 'Lines of Credit', 'Merchant Cash Advance'] },
  { slug: 'commercial-real-estate', title: 'Commercial Real Estate', needs: ['Acquisition', 'Bridge capital', 'Tenant improvements'], products: ['Commercial Real Estate Financing', 'SBA Loans', 'Lines of Credit'] },
];

export const blogPosts = [
  { slug: 'how-to-prepare-for-working-capital-application', title: 'How to Prepare for a Working Capital Application', description: 'A practical checklist for organizing revenue, bank statements, owner information, and use-of-funds details before applying for working capital.', author: 'Elite Funding Advisory Team', date: '2026-04-22', updated: '2026-05-06', minutes: 6, sections: [
    ['Start with a clear use of funds', 'Lenders want to understand whether proceeds support revenue-generating activity, stability, or expansion. Prepare a concise explanation that connects the requested amount to inventory, payroll, equipment, marketing, hiring, or other operating needs.'],
    ['Organize bank statements before submission', 'Complete statements help underwriting review deposit consistency, average balances, negative days, and returned items. Upload all pages for the most recent three months and confirm the business name matches the applicant.'],
    ['Confirm owner and business details', 'Validate legal business name, DBA, EIN, entity type, start date, ownership percentage, mobile phone, email, and business address before submission to reduce back-and-forth.'],
  ] },
  { slug: 'merchant-cash-advance-vs-business-line-of-credit', title: 'Merchant Cash Advance vs. Business Line of Credit', description: 'Understand key differences between merchant cash advances and business lines of credit, including speed, structure, cost considerations, and best-fit use cases.', author: 'Elite Funding Advisory Team', date: '2026-03-18', updated: '2026-04-29', minutes: 7, sections: [
    ['How structure differs', 'A merchant cash advance is typically repaid through fixed daily or weekly remittances tied to a purchased receivables amount. A business line of credit provides revolving access that can be drawn, repaid, and reused.'],
    ['When speed matters', 'MCA options can move quickly for businesses with strong deposits and urgent needs. Lines of credit may offer more flexibility for recurring needs but can require more underwriting review.'],
    ['Cost and control considerations', 'Compare total payback, repayment frequency, renewal flexibility, and cash-flow fit. The best structure depends on revenue consistency, timing, and whether capital is one-time or recurring.'],
  ] },
  { slug: 'documents-lenders-review-before-offer', title: 'Documents Lenders Review Before Issuing an Offer', description: 'Learn which documents lenders commonly review before presenting a business funding offer and how to avoid delays.', author: 'Elite Funding Advisory Team', date: '2026-02-27', updated: '2026-04-10', minutes: 5, sections: [
    ['Bank statements', 'Recent bank statements show deposit volume, balance trends, negative days, and cash-flow behavior. Missing pages or screenshots can slow review.'],
    ['Owner identification and business verification', 'Underwriters commonly verify the owner identity, business entity, EIN, address, and ownership percentage. Make sure submitted information matches official records.'],
    ['Product-specific documents', 'Equipment financing may require vendor quotes, invoice factoring may require A/R reports, and SBA or commercial real estate requests may require tax returns, financial statements, rent rolls, or property documents.'],
  ] },
];
