import type { Metadata } from 'next';
import { LegalPage } from '@/components/public/legal-page';
import { COMPANY } from '@/lib/company';

export const metadata: Metadata = { title: 'Privacy Policy | Elite Funding Solutions', description: 'How Elite Funding Solutions collects, uses, shares, retains, and safeguards application and website information.' };

export default function PrivacyPolicyPage() {
  return <LegalPage title="Privacy Policy" intro={`${COMPANY.name} respects privacy and protects nonpublic personal information submitted through our website, CRM, application workflow, and communications.`} sections={[
    { title: 'Information we collect', body: ['We collect business contact details, legal business name, DBA, entity type, EIN, industry, start date, addresses, phone numbers, email addresses, requested funding amount, use of funds, revenue, bank reference information, processing information, landlord or mortgage information, existing advance information, notes, uploaded documents, and other information you submit.', 'We collect owner and principal personal information including names, titles, ownership percentages, home addresses, email addresses, phone numbers, mobile numbers, dates of birth, SSN last four digits or other SSN information when requested, credit score ranges, identity documents, and signatures.'] },
    { title: 'Business application data and uploaded documents', body: ['Application data may include SSN, EIN, DOB, bank account and routing information, banking information, financial records, bank statements, processor statements, tax documents, voided checks, IDs, financial statements, and supporting documentation needed for underwriting, fraud prevention, document verification, funding, servicing, renewals, and compliance.'] },
    { title: 'Credit, background, SMS, analytics, and cookies', body: ['We collect credit and background authorization data, consumer reporting authorization records, business-report authorization records, signed names, timestamps, IP addresses, user agents, consent versions, and consent checkboxes.', 'When you opt in to text messaging, we collect SMS/text consent data including phone number, consent language, opt-in date, source, and opt-out requests. Reply STOP to opt out.', 'We use website analytics and cookies, including functional cookies, Google Analytics, advertising pixels such as Meta Pixel where configured, device data, pages viewed, referrers, approximate location, and similar technical information.'] },
    { title: 'How information is used', body: ['We use information to evaluate funding requests, verify identity and business information, obtain or review credit and business reports, obtain or review bank and processor statements, match applicants with lenders and funding partners, communicate about applications and offers, prevent fraud, improve the website and CRM, comply with law, maintain records, enforce agreements, and protect our rights and systems.'] },
    { title: 'How information is shared', body: ['We may share application and nonpublic personal information with lenders, funding partners, affiliates, service providers, credit bureaus, banks, processors, underwriting partners, document processors, CRM and hosting providers, email/SMS vendors, analytics providers, legal and compliance advisors, successors, assigns, agents, and other recipients involved in underwriting, funding, servicing, renewals, collections, compliance, fraud prevention, or transaction processing.', 'We do not sell applicant nonpublic personal information for unrelated consumer marketing. We limit sharing to legitimate business, funding, operational, compliance, and legally permitted purposes.'] },
    { title: 'GLBA-style privacy disclosures', body: ['We treat nonpublic personal information as confidential and restrict access to personnel, service providers, funding partners, and other recipients who need it for business purposes. We maintain administrative, technical, and physical safeguards designed to protect customer information and require service providers to protect information consistent with their roles.'] },
    { title: 'FTC Safeguards Rule data security', body: ['Because our workflow handles sensitive financial and identity information, we maintain a written information security program appropriate to our size, complexity, activities, and data. The program is designed to include risk assessment, access controls, encryption or masking where appropriate, secure development practices, audit logging, vendor oversight, incident response, employee access restrictions, and periodic review of safeguards.'] },
    { title: 'Consumer reporting authorization', body: ['When you submit an application and authorize us, you permit Elite Funding Solutions and its recipients, partners, successors, assigns, agents, affiliates, service providers, and funding partners to obtain consumer, personal, business, investigative, credit, processor, bank statement, bank, and financial reports for underwriting, funding, renewal, servicing, fraud prevention, and account-review purposes.'] },
    { title: 'Data retention and safeguards', body: ['We retain information for as long as reasonably necessary for application review, funding, servicing, legal, compliance, audit, fraud-prevention, dispute-resolution, and business-record purposes, unless a longer period is required or permitted by law.', 'Security safeguards include server-side submission, restricted document storage, role-based access, RLS-backed database access, audit logs, masking of sensitive fields in CRM views by default, and controls designed to prevent exposure of service role keys or sensitive data in client-side logs. No internet or storage system can be guaranteed 100% secure.'] },
    { title: 'User choices, email opt-out, and SMS opt-out', body: ['You may request access, correction, or deletion where legally available by contacting us. We may need to retain information for legal, underwriting, fraud-prevention, and business-record purposes.', 'Marketing emails will include opt-out instructions and a valid physical postal address. You may also contact us to opt out of marketing emails.', 'For SMS/text messages, reply STOP to opt out and HELP for help. Message and data rates may apply. Consent to marketing texts is not a condition of purchase where legally required.'] },
  ]} />;
}
