export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          domain: string | null;
          logo_url: string | null;
          brand_color: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          website: string | null;
          settings: Json;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['organizations']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['organizations']['Insert']>;
      };
      user_profiles: {
        Row: {
          id: string;
          user_id: string | null;
          organization_id: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          avatar_url: string | null;
          title: string | null;
          department: string | null;
          role: UserRole;
          permissions: string[];
          is_active: boolean;
          referral_slug: string | null;
          last_login_at: string | null;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['user_profiles']['Row'], 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'deleted_by'>;
        Update: Partial<Database['public']['Tables']['user_profiles']['Insert']>;
      };
      leads: {
        Row: {
          id: string;
          organization_id: string;
          lead_source: LeadSource;
          campaign: string | null;
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          business_name: string | null;
          status: LeadStatus;
          assigned_user_id: string | null;
          iso_broker_id: string | null;
          referral_code: string | null;
          referral_path: string | null;
          referred_by_user_profile_id: string | null;
          notes: string | null;
          tags: string[];
          next_follow_up_at: string | null;
          last_contacted_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['leads']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['leads']['Insert']>;
      };
      businesses: {
        Row: {
          id: string;
          organization_id: string;
          legal_name: string;
          dba: string | null;
          entity_type: EntityType | null;
          ein_encrypted: string | null;
          ein_hash: string | null;
          industry: string | null;
          naics_code: string | null;
          start_date: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          monthly_gross_revenue: number | null;
          average_daily_balance: number | null;
          deposit_count_monthly: number | null;
          current_processor: string | null;
          landlord_name: string | null;
          landlord_phone: string | null;
          rent_amount: number | null;
          has_tax_lien: boolean;
          has_bankruptcy: boolean;
          risk_flags: string[];
          notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['businesses']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['businesses']['Insert']>;
      };
      owners: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string | null;
          first_name: string;
          last_name: string;
          email: string | null;
          phone: string | null;
          dob_encrypted: string | null;
          ssn_last4: string | null;
          ownership_percentage: number | null;
          credit_score_range: CreditScoreRange | null;
          address: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['owners']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['owners']['Insert']>;
      };
      deals: {
        Row: {
          id: string;
          organization_id: string;
          application_id: string | null;
          business_id: string | null;
          lead_id: string | null;
          stage_id: string | null;
          stage_slug: string;
          title: string | null;
          requested_amount: number | null;
          approved_amount: number | null;
          funded_amount: number | null;
          funding_probability: number;
          assigned_user_id: string | null;
          junior_closer_id: string | null;
          senior_closer_id: string | null;
          iso_broker_id: string | null;
          lead_source: string | null;
          referral_code: string | null;
          referral_path: string | null;
          referred_by_user_profile_id: string | null;
          submission_sequence: number | null;
          duplicate_of_business_id: string | null;
          defaulted_at: string | null;
          default_reason: string | null;
          commission_clawback_amount: number | null;
          referral_partner_commission_pct: number | null;
          junior_closer_commission_pct: number | null;
          senior_closer_commission_pct: number | null;
          funded_at: string | null;
          declined_at: string | null;
          decline_reason: string | null;
          notes: string | null;
          tags: string[];
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['deals']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['deals']['Insert']>;
      };
      applications: {
        Row: {
          id: string;
          organization_id: string;
          business_id: string | null;
          lead_id: string | null;
          status: ApplicationStatus;
          requested_amount: number | null;
          use_of_funds: string | null;
          desired_timeline: string | null;
          has_existing_advances: boolean;
          desired_payment_frequency: string | null;
          notes: string | null;
          bank_name: string | null;
          account_type: string | null;
          routing_number: string | null;
          account_last4: string | null;
          avg_monthly_deposits: number | null;
          negative_days_count: number;
          nsf_count: number;
          ending_balance_estimate: number | null;
          submitted_at: string | null;
          ip_address: string | null;
          user_agent: string | null;
          assigned_user_id: string | null;
          iso_broker_id: string | null;
          lead_source: string | null;
          referral_code: string | null;
          referral_path: string | null;
          referred_by_user_profile_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['applications']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['applications']['Insert']>;
      };
      offers: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string;
          partner_submission_id: string | null;
          funding_partner_id: string | null;
          approved_amount: number;
          buy_rate: number | null;
          sell_rate: number | null;
          factor_rate: number | null;
          payback_amount: number | null;
          term_days: number | null;
          payment_frequency: string | null;
          daily_payment: number | null;
          weekly_payment: number | null;
          origination_fee: number;
          broker_commission_pct: number;
          iso_commission_pct: number;
          net_funding_amount: number | null;
          holdback_pct: number | null;
          stips_required: string[];
          expires_at: string | null;
          status: OfferStatus;
          presented_at: string | null;
          accepted_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['offers']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['offers']['Insert']>;
      };
      funding_partners: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          contact_name: string | null;
          email: string | null;
          phone: string | null;
          submission_email: string | null;
          portal_url: string | null;
          product_types: string[];
          min_funding_amount: number | null;
          max_funding_amount: number | null;
          min_monthly_revenue: number | null;
          min_time_in_business_months: number | null;
          min_credit_score: number | null;
          restricted_industries: string[];
          states_served: string[];
          avg_approval_days: number | null;
          commission_rules: Json;
          notes: string | null;
          is_active: boolean;
          deleted_at: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['funding_partners']['Row'], 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'deleted_by'>;
        Update: Partial<Database['public']['Tables']['funding_partners']['Insert']>;
      };
      documents: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          application_id: string | null;
          document_request_id: string | null;
          uploaded_by_user_id: string | null;
          document_type: string;
          label: string;
          file_name: string;
          file_size: number | null;
          mime_type: string | null;
          storage_path: string;
          status: DocumentStatus;
          reviewed_by: string | null;
          reviewed_at: string | null;
          review_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['documents']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['documents']['Insert']>;
      };
      tasks: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          application_id: string | null;
          business_id: string | null;
          lead_id: string | null;
          title: string;
          description: string | null;
          due_date: string | null;
          assigned_user_id: string | null;
          priority: TaskPriority;
          status: TaskStatus;
          completed_at: string | null;
          related_checklist_item_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['tasks']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['tasks']['Insert']>;
      };
      pipeline_stages: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          slug: string;
          color: string;
          position: number;
          is_terminal: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['pipeline_stages']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['pipeline_stages']['Insert']>;
      };
      underwriting_reviews: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string;
          application_id: string | null;
          assigned_underwriter_id: string | null;
          monthly_gross_revenue: number | null;
          average_daily_balance: number | null;
          deposit_count: number | null;
          nsf_count: number;
          negative_days: number;
          existing_advance_balance: number;
          existing_daily_payments: number;
          industry: string | null;
          time_in_business_months: number | null;
          credit_score_range: string | null;
          has_tax_lien: boolean;
          has_bankruptcy: boolean;
          document_completeness_pct: number;
          estimated_funding_min: number | null;
          estimated_funding_max: number | null;
          max_safe_payment_daily: number | null;
          estimated_factor_rate: number | null;
          estimated_payback_amount: number | null;
          estimated_daily_payment: number | null;
          estimated_weekly_payment: number | null;
          existing_payment_burden_pct: number | null;
          risk_tier: RiskTier | null;
          underwriting_score: number | null;
          renewal_eligible: boolean;
          risk_flags: string[];
          notes: string | null;
          decision: string | null;
          decision_at: string | null;
          decision_by: string | null;
          decision_notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['underwriting_reviews']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['underwriting_reviews']['Insert']>;
      };
      activities: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          application_id: string | null;
          business_id: string | null;
          owner_id: string | null;
          lead_id: string | null;
          activity_type: string;
          title: string;
          body: string | null;
          direction: string | null;
          performed_by: string | null;
          resource_type: string | null;
          resource_id: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['activities']['Row'], 'id' | 'created_at'>;
        Update: never;
      };
      messages: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          application_id: string | null;
          business_id: string | null;
          direction: string | null;
          channel: string | null;
          sender_user_id: string | null;
          recipient_user_id: string | null;
          recipient_email: string | null;
          recipient_phone: string | null;
          subject: string | null;
          body: string;
          delivery_status: string;
          sent_at: string | null;
          read_at: string | null;
          created_at: string;
          updated_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['messages']['Insert']>;
      };
      renewals: {
        Row: {
          id: string;
          organization_id: string;
          original_deal_id: string;
          new_deal_id: string | null;
          business_id: string | null;
          original_funded_amount: number | null;
          current_balance: number | null;
          payback_remaining: number | null;
          percent_paid_down: number | null;
          estimated_renewal_amount: number | null;
          status: string;
          renewal_date: string | null;
          assigned_user_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['renewals']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['renewals']['Insert']>;
      };
      commissions: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          offer_id: string | null;
          rep_id: string | null;
          iso_broker_id: string | null;
          funded_amount: number;
          commission_pct: number;
          commission_amount: number;
          payment_status: string;
          paid_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['commissions']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['commissions']['Insert']>;
      };
      iso_brokers: {
        Row: {
          id: string;
          organization_id: string;
          company_name: string;
          broker_name: string | null;
          email: string | null;
          phone: string | null;
          commission_pct: number;
          payment_terms: string | null;
          is_active: boolean;
          application_slug: string | null;
          deleted_at: string | null;
          deleted_by: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['iso_brokers']['Row'], 'id' | 'created_at' | 'updated_at' | 'deleted_at' | 'deleted_by'>;
        Update: Partial<Database['public']['Tables']['iso_brokers']['Insert']>;
      };
      contracts: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string;
          offer_id: string | null;
          contract_type: string;
          sent_date: string | null;
          signed_date: string | null;
          status: ContractStatus;
          storage_path: string | null;
          signed_storage_path: string | null;
          funding_date: string | null;
          funded_amount: number | null;
          notes: string | null;
          docusign_envelope_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['contracts']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['contracts']['Insert']>;
      };
      stipulations: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          offer_id: string | null;
          name: string;
          required_by_partner: string | null;
          due_date: string | null;
          status: StipStatus;
          assigned_user_id: string | null;
          document_id: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['stipulations']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['stipulations']['Insert']>;
      };
      document_requests: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          application_id: string | null;
          document_type: string;
          label: string;
          description: string | null;
          required: boolean;
          status: DocRequestStatus;
          due_date: string | null;
          assigned_user_id: string | null;
          notes: string | null;
          category: string;
          related_document_id: string | null;
          waived_by: string | null;
          waived_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: Omit<Database['public']['Tables']['document_requests']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['document_requests']['Insert']>;
      };
      partner_submissions: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string;
          funding_partner_id: string;
          submitted_by: string | null;
          submitted_at: string | null;
          status: string;
          decline_reason: string | null;
          response_date: string | null;
          notes: string | null;
          conditions: string | null;
          custom_message: string | null;
          attachment_document_ids: string[];
          email_subject: string | null;
          generated_email_body: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['partner_submissions']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['partner_submissions']['Insert']>;
      };
      document_upload_tokens: {
        Row: {
          id: string;
          token_hash: string;
          organization_id: string;
          deal_id: string;
          application_id: string | null;
          expires_at: string;
          used_at: string | null;
          created_by: string | null;
          allowed_document_request_ids: string[];
          revoked_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['document_upload_tokens']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['document_upload_tokens']['Insert']>;
      };
      crm_settings: {
        Row: {
          id: string;
          organization_id: string;
          setting_key: string;
          setting_value: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['crm_settings']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['crm_settings']['Insert']>;
      };
      audit_logs: {
        Row: {
          id: string;
          organization_id: string | null;
          user_id: string | null;
          actor_user_id: string | null;
          action: string;
          resource_type: string;
          resource_id: string | null;
          old_data: Json | null;
          new_data: Json | null;
          metadata: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['audit_logs']['Row'], 'id' | 'created_at'>;
        Update: never;
      };
    };
    Views: {
      deal_summary_view: {
        Row: {
          id: string;
          organization_id: string;
          stage_slug: string;
          requested_amount: number | null;
          approved_amount: number | null;
          funded_amount: number | null;
          funding_probability: number;
          created_at: string;
          updated_at: string;
          business_name: string | null;
          business_dba: string | null;
          monthly_gross_revenue: number | null;
          industry: string | null;
          assigned_rep_name: string | null;
          assigned_rep_email: string | null;
          document_count: number | null;
          missing_documents: number | null;
          active_offer_count: number | null;
        };
      };
    };
    Functions: {
      get_dashboard_metrics: {
        Args: { p_org_id: string };
        Returns: Json;
      };
      repair_user_profile: {
        Args: { p_user_id: string; p_email: string; p_org_id?: string; p_role?: string };
        Returns: string;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// Type aliases
export type UserRole = 'super_admin' | 'admin' | 'manager' | 'sales_rep' | 'underwriter' | 'processor' | 'iso_broker' | 'client' | 'viewer';
export type LeadSource = 'website' | 'referral' | 'broker' | 'iso' | 'paid_ads' | 'organic_search' | 'cold_email' | 'partner' | 'manual_entry';
export type LeadStatus = 'new' | 'contacted' | 'qualified' | 'application_started' | 'converted' | 'lost' | 'unresponsive';
export type EntityType = 'sole_proprietor' | 'llc' | 's_corp' | 'c_corp' | 'partnership' | 'non_profit' | 'other';
export type CreditScoreRange = 'below_500' | '500_549' | '550_599' | '600_649' | '650_699' | '700_749' | '750_plus';
export type ApplicationStatus = 'started' | 'submitted' | 'under_review' | 'approved' | 'declined' | 'withdrawn';
export type OfferStatus = 'received' | 'presented' | 'accepted' | 'rejected' | 'expired' | 'withdrawn';
export type DocumentStatus = 'uploaded' | 'in_review' | 'approved' | 'rejected' | 'needs_replacement' | 'expired';
export type DocRequestStatus = 'missing' | 'requested' | 'uploaded' | 'received' | 'in_review' | 'approved' | 'rejected' | 'needs_replacement' | 'waived';
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';
export type TaskStatus = 'open' | 'in_progress' | 'completed' | 'cancelled';
export type RiskTier = 'A' | 'B' | 'C' | 'D' | 'decline';
export type ContractStatus = 'draft' | 'sent' | 'viewed' | 'signed' | 'rejected' | 'expired' | 'funded';
export type StipStatus = 'needed' | 'requested' | 'received' | 'approved' | 'rejected' | 'waived';

// Convenience row types used by the current CRM UI.
// The screens intentionally consume denormalized fields from joins/views while the schema is still evolving.
export type DbRecord = Record<string, any>;
export type Organization = DbRecord;
export type UserProfile = DbRecord;
export type Lead = DbRecord;
export type Business = DbRecord;
export type Owner = DbRecord;
export type Deal = DbRecord;
export type Application = DbRecord;
export type Offer = DbRecord;
export type FundingPartner = DbRecord;
export type Document = DbRecord;
export type Task = DbRecord;
export type Activity = DbRecord;
export type Message = DbRecord;
export type Renewal = DbRecord;
export type Commission = DbRecord;
export type IsoBroker = DbRecord;
export type Contract = DbRecord;
export type Stipulation = DbRecord;
export type UnderwritingReview = DbRecord;
export type PipelineStage = DbRecord;
export type DealSummary = DbRecord;
