import Link from 'next/link';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { industries, fundingSolutions } from '@/lib/content/site';
import { pageMeta } from '@/lib/seo';
export function generateStaticParams() { return industries.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: { params: { slug: string } }): Metadata { const item = industries.find((industry) => industry.slug === params.slug); return item ? pageMeta({ title: `${item.title} Business Funding | Elite Funding Solutions`, description: `Funding options for ${item.title.toLowerCase()} businesses, including ${item.products.join(', ')}.`, path: `/industries/${item.slug}` }) : {}; }
export default function IndustryPage({ params }: { params: { slug: string } }) { const item = industries.find((industry) => industry.slug === params.slug); if (!item) notFound(); return <main className="bg-[#040B16] text-white"><section className="container-page py-20"><Link href="/industries" className="text-sm font-semibold text-[#E3C77A]">All industries</Link><h1 className="mt-6 max-w-4xl font-display text-[48px] font-semibold leading-tight md:text-[68px]">{item.title} business funding</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-[#B9C2D0]">Capital strategies for common {item.title.toLowerCase()} needs, from cash-flow timing to equipment, inventory, staffing, and expansion.</p></section><section className="container-page grid gap-6 pb-20 lg:grid-cols-3"><Info title="Common funding needs" items={item.needs} /><Info title="Relevant products" items={item.products} /><Info title="How Elite helps" items={['Advisor-guided intake and packaging', 'Side-by-side offer comparison', 'Secure document workflow']} /></section><section className="container-page pb-20"><div className="rounded-[28px] border border-[#C9A45C]/20 bg-[#101D2F] p-8"><h2 className="font-display text-3xl font-semibold">Funding options for {item.title.toLowerCase()}</h2><p className="mt-2 text-[#B9C2D0]">Explore product details or submit one secure application to identify available options.</p><div className="mt-6 flex flex-wrap gap-3">{item.products.map((product) => { const match = fundingSolutions.find((solution) => solution.title === product); return <Link key={product} href={match ? `/funding-solutions/${match.slug}` : '/funding-solutions'} className="rounded-sm border border-[#C9A45C]/40 px-4 py-2 text-sm text-[#E3C77A]">{product}</Link>; })}<Link href="/apply" className="rounded-sm bg-[#C9A45C] px-4 py-2 text-sm font-bold text-[#07111F]">Apply now</Link></div></div></section></main>; }
function Info({ title, items }: { title: string; items: string[] }) { return <div className="rounded-2xl border border-white/10 bg-[#07111F] p-6"><h2 className="font-display text-2xl font-semibold text-[#E3C77A]">{title}</h2><ul className="mt-4 space-y-3 text-[#B9C2D0]">{items.map((item) => <li key={item} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-[#C9A45C]" />{item}</li>)}</ul></div>; }
